application: devfest2013-pagespeed
version: 2013-1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
# re-direct to index.html if no path is give
- url: /
  static_files: index.html
  upload: index.html
  expiration: "5m"
  
# re-direct to index.html
- url: /index.html(.*)
  static_files: index.html
  upload: index.html(.*)
  expiration: "5m"

# access the static resources in the root director

- url: /(.*)
  static_files: \1
  upload: (.*)
  
pagespeed:
  domains_to_rewrite:
  
  url_blacklist:
  
  enabled_rewriters:
  - MinifyCss
  - RemoveComments
  disabled_rewriters:
  - ImageStripColorProfile